# Generated by Django 4.1.4 on 2022-12-22 12:59

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ordering', models.TextField(default='')),
            ],
            options={
                'ordering': ['-created_at', 'updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_post', to='business.business')),
            ],
            options={
                'ordering': ['-created_at', 'updated_at'],
                'abstract': False,
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'updated_at'],
                'abstract': False,
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='UserPostSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('content', models.CharField(blank=True, max_length=256, null=True)),
                ('source_type', models.CharField(choices=[('photo', 'photo'), ('video', 'video')], default='photo', max_length=8)),
                ('source', core.fields.UniqueNameFileField(upload_to=posts.models.user_post_source_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='posts.userpost')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessPostSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('content', models.CharField(blank=True, max_length=256, null=True)),
                ('source_type', models.CharField(choices=[('photo', 'photo'), ('video', 'video')], default='photo', max_length=8)),
                ('source', core.fields.UniqueNameFileField(upload_to=posts.models.business_post_source_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_post', to='posts.businesspost')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
