# Generated by Django 4.1.4 on 2023-01-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspostslice',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='userpostslice',
            name='source_type',
        ),
    ]
