# Generated by Django 4.1.4 on 2023-01-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registrationtoken_remove_tokencode_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
