# Generated by Django 4.1.4 on 2023-01-05 01:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtoken',
            name='qrcode',
            field=models.ImageField(default=None, upload_to=users.models.upload_qr_code),
        ),
    ]
