# Generated by Django 4.1.4 on 2023-01-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_registrationtoken_qrcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationToken',
            new_name='AccessToken',
        ),
        migrations.AlterUniqueTogether(
            name='accesstoken',
            unique_together={('email', 'value')},
        ),
    ]
