# Generated by Django 4.1.4 on 2022-12-22 12:58

import core.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import moments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=None)),
                ('time', models.TimeField(default=None)),
                ('title', models.CharField(default=None, max_length=32)),
                ('guests', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.CharField(blank=True, max_length=64, null=True)),
                ('instagram', models.CharField(blank=True, max_length=64, null=True)),
                ('website', models.CharField(blank=True, max_length=64, null=True)),
                ('ticket', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('reposts_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('business', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='business_moment', to='business.business')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.location')),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventMomentSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('source', core.fields.UniqueNameFileField(upload_to=moments.models.event_moment_source_path)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_moment_slice', to='moments.eventmoment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('url_tag', models.TextField(blank=True, default=None, max_length=512, null=True, validators=[django.core.validators.URLValidator()])),
                ('content', core.fields.TextField(blank=True, max_length=300, null=True)),
                ('source', core.fields.UniqueNameFileField(blank=True, upload_to=moments.models.user_moment_source_path)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('end_at', models.DateTimeField(default=None)),
                ('business_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_business_tag', to='business.business')),
                ('event_moment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moments.eventmomentslice')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_moment_location', to='shared.location')),
                ('location_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_location_tag', to='shared.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_moment', to=settings.AUTH_USER_MODEL)),
                ('users_tag', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='eventmoment',
            index=models.Index(fields=['date', 'business'], name='moments_eve_date_6bdc73_idx'),
        ),
    ]
