version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env/.prod.env
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: postgis/postgis
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data/
    env_file:
      - .env/.prod.env

  redis:
    image: "bitnami/redis:latest"
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env/.prod.env

  worker:
    build: .
    restart: unless-stopped
    entrypoint: /app/scripts/celery-worker-entrypoint.sh
    depends_on:
      - app
      - redis
      - database
    env_file:
      - .env/.prod.env

volumes:
  database_data:
