version: "3.9"

services:
  app:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  database:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGERS_DB=database

  redis:
    image: "bitnami/redis:latest"
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  nsfw:
    image: eugencepoi/nsfw_api
    ports:
      - "5000:5000"
    depends_on:
      - app
    environment:
      - PORT=5000

volumes:
  postgres_data:
