# Generated by Django 4.1.4 on 2022-12-22 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('moments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_event', to='moments.eventmoment')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventRepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_event', to='moments.eventmoment')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='business_%(class)s', to='business.business')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessRepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='business_%(class)s', to='business.business')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessProfileVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='business_%(class)s', to='business.business')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='business_%(class)s', to='business.business')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='eventshare',
            index=models.Index(fields=['event', 'created_at'], name='insights_ev_event_i_4202c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventshare',
            unique_together={('user', 'event', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='eventrepost',
            index=models.Index(fields=['event', 'created_at'], name='insights_ev_event_i_0f1266_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventrepost',
            unique_together={('user', 'event', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='businessshare',
            index=models.Index(fields=['business', 'created_at'], name='insights_bu_busines_7f28ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessshare',
            unique_together={('user', 'business', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='businessrepost',
            index=models.Index(fields=['business', 'created_at'], name='insights_bu_busines_c428b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessrepost',
            unique_together={('user', 'business', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='businessprofilevisit',
            index=models.Index(fields=['business', 'created_at'], name='insights_bu_busines_1dae63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessprofilevisit',
            unique_together={('user', 'business', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='businesslike',
            index=models.Index(fields=['business', 'created_at'], name='insights_bu_busines_34b403_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businesslike',
            unique_together={('user', 'business', 'created_at')},
        ),
    ]
