# Generated by Django 4.1.4 on 2022-12-22 12:55

import business.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(default=None, max_length=32)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None)),
                ('timetable', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('price_target', models.IntegerField(blank=True, default=2, null=True)),
                ('menu_url', models.TextField(blank=True, null=True)),
                ('ticket_url', models.TextField(blank=True, null=True)),
                ('web_url', models.TextField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=64, null=True)),
                ('nearby_info', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('allow_chat', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('cover_source', models.ImageField(upload_to=business.models.business_source_path)),
                ('settings', models.JSONField(blank=True, default=business.models.get_default_settings, null=True)),
                ('public_key', models.TextField(blank=True, default=None, max_length=64, null=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='business_amenities', to='shared.amenity')),
                ('categories', models.ManyToManyField(blank=True, related_name='business_categories', to='shared.businesscategory')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, related_name='business_main_category', to='shared.businesscategory')),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_likes', to='shared.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessToken',
            fields=[
                ('key', models.CharField(default=business.models.generate_key, max_length=40, primary_key=True, serialize=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(condition=models.Q(('is_approved', True)), fields=['id'], name='business_id_part_ix'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(condition=models.Q(('is_approved', True)), fields=['location'], name='business_location_part_ix'),
        ),
    ]
